{{ if eq .Values.components.app_be_api_gateway.deploy "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.components.app_be_api_gateway.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.components.app_be_api_gateway.appName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.components.app_be_api_gateway.appName }}
    spec:
      containers:
        - name: {{ .Values.components.app_be_api_gateway.appName }}
          image: {{ .Values.components.app_be_api_gateway.image.name }}:{{ .Values.components.app_be_api_gateway.image.version }}
          imagePullPolicy:  {{ .Values.components.app_be_api_gateway.image.policy }}
          ports:
            - containerPort:  {{ .Values.components.app_be_api_gateway.port.container }}
              protocol: TCP
          env:
            - name: NEST_APP_NAME
              value: {{ .Values.components.app_be_api_gateway.appName }}
            - name: NEST_API_PORT
              value: {{ quote .Values.components.app_be_api_gateway.env.apiPort }}
            - name: NEST_MQ_CONNECTION_STRING
              value: {{ .Values.components.app_be_api_gateway.env.messageQueuConnectionString }}
{{ end }}