### Registrate a user
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "Attila Molnar",
    "userName": "molnara2aaa",
    "password": "1234",
    "email": "email@email.com"
}

### User login
# @name login
POST http://localhost:3002/auth/login HTTP/1.1
content-type: application/json

{
    "username": "email@email.com",
    "password": "1234"
}

### User validation
GET http://localhost:3002/ HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}

### User validation
GET http://localhost:3000/ HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}