# Default values for project-infra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

components:

## Redis overwirte
redis:
  auth:
    enabled: false
  replica:
    replicaCount: 1
  master:
    count: 1
    service:
      type: NodePort