# Default values for project-infra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

components:

## Redis overwirte
redis:
  replica:
    replicaCount: 1
  master:
    count: 1
    service:
      type: LoadBalancer
# kubemq:
#   grpc:
#     expose: LoadBalancer
#   key: 3a561dc1-0454-4895-9eb7-8c9308afb14a