# Default values for project-practise.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

components:
  app_be_api_gateway:
    appName: "app-be-api-gateway"
    image:
      name: "app-be-api-gateway"
      version: "v1.0.3"
      policy: "IfNotPresent"
    port:
      port: 3000
      target: 3000
      container: 3000
    env:
      apiPort: "3000"
      messageQueuConnectionString: "kubemq-cluster-grpc.kubemq:50000"

  app_be_authentication:
    appName: "app-be-authentication"
    image: 
      name: "app-be-authentication"
      version: "v1.0.1"
      policy: "IfNotPresent"
    port: 
      port: 3002
      target: 3002
      container: 3002
    env:
      apiPort: "3002"
      messageQueuConnectionString: "kubemq-cluster-grpc.kubemq:50000"
      mongodbConnectionString: "mongodb+srv://attila:Idq2fdKRxWMceDx4@cluster0.ml4i0.mongodb.net/nestjs-practise?retryWrites=true&w=majority"

  app_be_user:
    appName: "app-be-user"
    image: 
      name: "app-be-user"
      version: "v1.0.4"
      policy: "IfNotPresent"
    port: 
      port: 3001
      target: 3001
      container: 3001
    env:
      apiPort: "3001"
      messageQueuConnectionString: "kubemq-cluster-grpc.kubemq:50000"
      mongodbConnectionString: "mongodb+srv://attila:Idq2fdKRxWMceDx4@cluster0.ml4i0.mongodb.net/nestjs-practise?retryWrites=true&w=majority"