{{ if eq .Values.components.app_be_authentication.deploy "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.components.app_be_authentication.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.components.app_be_authentication.appName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.components.app_be_authentication.appName }}
    spec:
      containers:
        - name: {{ .Values.components.app_be_authentication.appName }}
          image: {{ .Values.components.app_be_authentication.image.name }}:{{ .Values.components.app_be_authentication.image.version }}
          imagePullPolicy:  {{ .Values.components.app_be_authentication.image.policy }}
          ports:
            - containerPort:  {{ .Values.components.app_be_authentication.port.container }}
              protocol: TCP
          env:
            - name: NEST_APP_NAME
              value: {{ .Values.components.app_be_authentication.appName }}
            - name: NEST_API_PORT
              value: {{ quote .Values.components.app_be_authentication.env.apiPort }}
            - name: NEST_MQ_CONNECTION_STRING
              value: {{ .Values.components.app_be_authentication.env.messageQueuConnectionString }}
            - name: NEST_MONGODB_CONNECTION_STRING
              value: {{ .Values.components.app_be_authentication.env.mongodbConnectionString }}
            - name: NEST_MONGODB_DB_NAME
              value: {{ .Values.components.app_be_authentication.env.mongodbName }}
            - name: NEST_REDIS_HOST
              value: {{ .Values.components.app_be_authentication.env.redis.host }}
            - name: NEST_REDIS_PORT
              value: {{ quote .Values.components.app_be_authentication.env.redis.port }}
            - name: NEST_REDIS_PASSWORD
              value: {{ .Values.components.app_be_authentication.env.redis.password }}
{{ end }}