{{ if eq .Values.components.app_be_authentication.deploy "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.components.app_be_authentication.appName }}
spec:
  selector:
    app: {{ .Values.components.app_be_authentication.appName }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.components.app_be_authentication.port.port }}
      targetPort: {{ .Values.components.app_be_authentication.port.target }}
  type: LoadBalancer
{{ end }}