apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.components.app_be_user.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.components.app_be_user.appName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.components.app_be_user.appName }}
    spec:
      containers:
        - name: {{ .Values.components.app_be_user.appName }}
          image: {{ .Values.components.app_be_user.image.name }}:{{ .Values.components.app_be_user.image.version }}
          imagePullPolicy:  {{ .Values.components.app_be_user.image.policy }}
          ports:
            - containerPort:  {{ .Values.components.app_be_user.port.container }}
              protocol: TCP
          env:
            - name: NEST_APP_NAME
              value: {{ .Values.components.app_be_user.appName }}
            - name: NEST_API_PORT
              value: {{ quote .Values.components.app_be_user.env.apiPort }}
            - name: NEST_MQ_CONNECTION_STRING
              value: {{ .Values.components.app_be_user.env.messageQueuConnectionString }}
            - name: NEST_MONGODB_CONNECTION_STRING
              value: {{ .Values.components.app_be_user.env.mongodbConnectionString }}
            - name: NEST_MONGODB_DB_NAME
              value: {{ .Values.components.app_be_user.env.mongodbName }}